#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"

# This is used to determine if a monitor is used
# Since the notch is -only- on the laptop, if a monitor isn't used,
# then that means the internal display is used ¯\_(ツ)_/¯
#!/usr/bin/env zsh
FONT_FACE="JetBrainsMono Nerd Font"
ICON_FONT_FACE="Symbols Nerd Font Mono"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
source "$PLUGIN_SHARED_DIR/colors.sh"
source "$PLUGIN_SHARED_DIR/icons.sh"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    display=all \
    height=32 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=5 \
    padding_right=5 \
    notch_width=188 \

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
# background.color=0x66494d64 \
sketchybar --default \
    background.color=0x9924273a \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5 \
    --subscribe system_woke

# sketchybar --add item current_space left \
#     --set current_space \
#     background.color=0xfff5a97f \
#     icon.color=0xff24273a \
#     label.drawing=off \
#     script="$PLUGIN_SHARED_DIR/current_space.sh" \
#     --subscribe current_space front_app_switched mouse.clicked 


sketchybar --add event window_change
simple=(
    background.height=12                       \
    icon.padding_left=0                        \
    icon.padding_right=0                       \
    label.padding_left=0                       \
    label.padding_right=10   \
    background.border_width=0 
)
app_mode=(
    icon.font.size=12                               \
    icon.padding_left=5                        \
    icon.padding_right=5                       \
    label.padding_left=2                       \
    label.padding_right=5   \
    label.y_offset=1 \
    label.font="$ICON_FONT_FACE" \
    label.font.size=12 \
    background.border_width=0 
)

for i in {0..10};
do
  sid=$(($i+1))
  PAD_LEFT=4
  if [[ $i == 0 ]]; then
    PAD_LEFT=8
  elif [[ $i == $(($LENGTH-1)) ]]; then
    PAD_RIGHT=10
  fi

  sketchybar --add space space.$sid left                                       \
             --set       space.$sid                                            \
                script="$PLUGIN_SHARED_DIR/app_space_display.sh"                   \
                                    associated_space=$sid                      \
                                    background.border_width=2                  \
                                    background.corner_radius=6                 \
                                    "${app_mode[@]}"                     \
             --subscribe space.$sid front_app_switched 
done

sketchybar --add bracket spaces '/space\..*/' \
    script="$PLUGIN_SHARED_DIR/spaces.sh" \
    --subscribe spaces front_app_switched window_change mouse.clicked

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    background.padding_left=3 \
    scroll_texts=yes \
    label.max_chars=30 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item sep_left left \
    --set sep_left \
    background.color=0x00000000 \
    background.padding_left=0 \
    background.padding_right=0 \
    width=5

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.padding_left=7 \
    icon.padding_right=7 \
    icon.color=0xff24273a \
    icon.font="$ICON_FONT_FACE" \
    icon.font.size=12 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    background.padding_left=5 \
    scroll_texts=yes \
    label.y_offset=1 \
    label.max_chars=30 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=yes

sketchybar --add item weather q \
    --set weather \
    icon.color=0xfff5bde6 \
    background.padding_right=0 \
    icon.font="$FONT_FACE:Bold:15.0" \
    update_freq=1800 \
    scroll_texts=yes \
    label.max_chars=30 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    label.padding_right=3 \
    --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.name \
    --subscribe front_app front_app_switched

# sketchybar --add item notifications right \
#     --set notifications \
#     icon.color=0xffed8796 \
#     script="$PLUGIN_SHARED_DIR/notifications.sh" \
#     --subscribe mouse.clicked

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    background.padding_right=0 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item sep_right right \
    --set sep_right \
    background.color=0x00000000 \
    background.padding_left=0 \
    background.padding_right=0 \
    width=5

sketchybar --add item battery right \
    --set battery \
    background.color=0x00000000 \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    background.color=0x00000000 \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change mouse.clicked

cpu=(
	label=CPU%
	label.color="$LABEL_COLOR"
	icon="$CPU"
	icon.color="$BLUE"
	update_freq=15
	mach_helper="$HELPER"
	script="$PLUGIN_SHARED_DIR/cpu.sh"
)

# sketchybar 	--add item cpu.percent right 					\
#     background.color=0x00000000 \
# 						--set cpu.percent "${cpu[@]}"

memory=(
	label.color="$TEXT"
	icon="$MEMORY"
	icon.color="$GREEN"
	update_freq=15
	script="$PLUGIN_SHARED_DIR/ram.sh"
)

sketchybar 	--add item cpu.percent right 					\
			--set cpu.percent "${cpu[@]}" \
            background.color=0x00000000 \
            --add item memory right 		\
			--set memory "${memory[@]}" \
            background.color=0x00000000 \

    
sketchybar --add bracket right_bracket \
    battery \
    volume \
    cpu.percent \
    memory

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change display_change
